---
- hosts: all
  become: true
  tasks:
        - name: Flush IPtables
          iptables:
                  flush: yes

        - name: Set Legacy IPTables
          command: update-alternatives --set iptables /usr/sbin/iptables-legacy
        
        - name: Set Legacy IP6Tables
          command: update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
        - name: reboot
          reboot:

        - name: Download Installer Script
          get_url:
                  url: https://get.k3s.io
                  dest: /tmp/k3s_installer.sh

        - name: Execute Installer Script
          shell: K3S_KUBECONFIG_MODE="644" sh /tmp/k3s_installer.sh
          register: script_output

        - name: Display Script output
          debug: msg="{{ script_output.stdout }}"

        - name: Display Token
          debug: var=item
          with_file: "/var/lib/rancher/k3s/server/node-token"   
